const images = [
    {
        id:1,
        image:'imageMenu/affogato.jpg'
    },
    {
        id:2,
        image:'imageMenu/americano.jpg'
    },
    {
        id:3,
        image:'imageMenu/cappuccino.jpg'
    },
    {
        id:4,
        image:'imageMenu/cortado.jpg'
    },
    {
        id:5,
        image:'imageMenu/espresso.jpg'
    },
    {
        id:6,
        image:'imageMenu/flat-white.jpg'
    },
    {
        id:7,
        image:'imageMenu/latte.jpg'
    },
    {
        id:8,
        image:'imageMenu/macchiato.jpg'
    },
    {
        id:9,
        image:'imageMenu/mocaccino.jpg'
    },
    {
        id:10,
        image:'imageMenu/ristretto.jpg'
    },
]

export default images;